# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-WL7DcMeLofAjQkMhclZsqj2BLbbAZkv
"""

import requests
import pandas as pd

import yfinance as yf
df = yf.download("TWTR")

close = df['Close'].tolist()
volume = df['Volume'].tolist()
requests.get('http://localhost:8005/balance').json()

import json

data = json.dumps([close[0], volume[0]])
data
requests.get('http://localhost:8005/trade?data='+data).json()


for i in range(200):
    data = json.dumps([close[i], volume[i]])
    requested = requests.get('http://localhost:8005/trade?data=' + data).json()
    print(requested)
